apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave-spring-boot
  namespace: jenkins
  labels:
    name: jenkins-slave-spring-boot   
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4-jdk11
    command: ["/bin/sh","-c"]
    args: ["sleep 30; /usr/local/bin/jenkins-agent"]
  - name: maven-11
    image: maven:3.6.0-jdk-11	
    command:
    - cat
    tty: true  
  - name: maven-8
    image: maven:3.6.0-jdk-8      
    securityContext:
      privileged: true   	
    command:
    - cat
    tty: true